import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#570005",
        "primary-container": "#7B1113",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb3ac",
        "on-primary-fixed": "#410003",
        "on-primary-fixed-variant": "#891c1b",
        "on-primary-container": "#ff837a",
        secondary: "#066c4e",
        "secondary-container": "#9ff4ce",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#147254",
        "secondary-fixed": "#9ff4ce",
        "secondary-fixed-dim": "#83d7b3",
        tertiary: "#3c2100",
        "tertiary-container": "#5a3400",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#e3973a",
        "tertiary-fixed": "#ffdcbb",
        "tertiary-fixed-dim": "#ffb869",
        surface: "#fcf9f1",
        "surface-dim": "#dcdad2",
        "surface-bright": "#fcf9f1",
        "surface-variant": "#e5e2da",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f4eb",
        "surface-container": "#f0eee5",
        "surface-container-high": "#eae8e0",
        "surface-container-highest": "#e5e2da",
        "on-surface": "#1c1c17",
        "on-surface-variant": "#58413f",
        "on-background": "#1c1c17",
        background: "#fcf9f1",
        outline: "#8b716e",
        "outline-variant": "#dfbfbc",
        "inverse-surface": "#31312b",
        "inverse-on-surface": "#f3f1e8",
        "inverse-primary": "#ffb3ac",
        "surface-tint": "#aa3530",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        // Subject colors
        "subject-science": "#1D9E75",
        "subject-math": "#7F77DD",
        "subject-language": "#D85A30",
        "subject-reading": "#BA7517",
        "subject-mock": "#888780",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["'Courier New'", "monospace"],
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(28, 28, 23, 0.06)",
        "ambient-md": "0 8px 24px rgba(28, 28, 23, 0.08)",
        "ambient-lg": "0 32px 64px rgba(28, 28, 23, 0.1)",
      },
      animation: {
        "fade-up": "fadeUp 0.5s ease forwards",
        "fade-in": "fadeIn 0.4s ease forwards",
        "scale-in": "scaleIn 0.3s ease forwards",
        shimmer: "shimmer 2s infinite",
        "pulse-slow": "pulse 3s infinite",
        float: "float 6s ease-in-out infinite",
        "spin-slow": "spin 8s linear infinite",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        scaleIn: {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
